spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/daily_planner
    username: planner_user
    password: planner_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
